### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by nickmer99** [jaku/SnapCameraPreservation#10]
Would it be feasible to create a local backup of all the filters, in case something happens to your server in the coming months/years?

Thanks, 

- Nick

**Comment by jaku** [comment]
Local backup, not without some changes to the current server code. I know one of the forks https://github.com/AmayaWinter/SnapCameraPreservation of this project seemed to be looking to do that. 

In either case you'd need the original files which are now available though a torrent, but it's the whole collection of lenses so it's gonna come in at about 180GB or so.

https://twitter.com/J0hnnyXm4s/status/1619369852128591873
