### ISSUE TITLE
[Idea] Package this as a plugin for OBS Studio

### ISSUE THREAD

**Issue by nileshtrivedi** [jaku/SnapCameraPreservation#11]
This is not a feature request because what I'm suggesting is A LOT of work. But I think it would be worth building an open-source version of this app. [OBS Studio](https://obsproject.com/) already works as a virtual camera. If we can extract the ML models from Snap Camera app, it should be possible to support all the lenses as filters/effects in OBS.

Apologies if this discussion is not welcome here. Feel free to close.

**Comment by MissCurlyBlonde** [comment]
God I'd love for this to be possible.

**Comment by jaku** [comment]
Leaving this open just because this repo will most likely get the most eyes and attention for something like this.

This goes beyond the scope of this project and while it would be great, it would take a lot of work as you mentioned.

Anyone that is reading this and hoping for a solution, try to not get your hopes up as it would be a huge undertaking and would need some talented people to come together to complete it. I don't mean to be a pessimist on this, but it'd most likely be easier to rebuild something and get a new open lens format open than take on a project like this.

**Comment by nileshtrivedi** [comment]
> a new open lens format

IMHO, it's the machine-learning models that can track body parts which are the valuable bits in Snap Camera. It can be hard for a solo dev to build, train and optimize similar models from scratch.

**Comment by YorVeX** [comment]
> > a new open lens format
> 
> IMHO, it's the machine-learning models to track body parts which are the valuable bits in Snap Camera. It can be hard for a solo dev to build, train and optimize similar models from scratch.

While I never played with one myself I think there are quite a few open source solutions that can already do this, the most popular one being OpenCV. So maybe this part is not even as hard as we might think right now?

The other important part would be to be able to read and apply the lenses to that face/body model. One option would be to invoke Snap Cameras own libraries by a third party tool (or an OBS plugin), if someone figures out how to do that we wouldn


One option to achieve that would be to decipher the lens format and then code something to apply this. On the deciphering part [it seems someone is already making good progress on this](https://www.reddit.com/r/snapcamera/comments/10uitey/unpacking_lenslns_files_file_format_resolved/). The applying part might be a different story though.

Another option would be to write a third party tool or, as suggested here, an OBS plugin, that invokes Snap Camera's library files, something that also [someone has started to look into](https://gist.github.com/AaronC81/777be7d8d9cde29de92533d071c41766).

So the options are there, but I still agree that we shouldn't be too optimistic about it for now, it most probably is still a long way to go.
