### ISSUE TITLE
Adding lenses / filters that we have saved in our cache ?

### ISSUE THREAD

**Issue by MissCurlyBlonde** [jaku/SnapCameraPreservation#13]
Are you able to inject into your repository the lenses that we have saved in our cache before SnapCam closing down ? 
If yes, where should we send the zip file ?

**Comment by jaku** [comment]
Cached lenses do not follow the same format as those stored on the server.

When we download lenses from the server, the application converts it to the format that is then saved on the computer, and at this time we do not know of a way to convert them between formats.
