### ISSUE TITLE
Block while gaming

### ISSUE THREAD

**Issue by EnderGirl1500** [jaku/SnapCameraPreservation#14]
Hi! I don't know if it's my PC, the game I've just opened after applying the patch or the patch itself. I was sharing cam on Discord and as soon as I opened the game my camera froze for a couple of seconds and then showed the Snap Cam logo. If I switch tabs, the camera goes back to normal. But as soon as I click on the game, it freezes again.

**Comment by jaku** [comment]
The camera source for the virtual camera is a different process/service than the one we patch. This issue would have the same problem on the official client. All we change with the patch is the hostname the application communicates with.

**Comment by EnderGirl1500** [comment]
That's the thing, I've never had this problem before

**Comment by jaku** [comment]
Try restarting your computer and see if it persists but as mentioned we only changed the host the application communicates with and once a lens is applied the app doesn't make any more requests until the lens is disabled or another is applied.
