### ISSUE TITLE
Modified version of Snap Camera  suddenly stopped working and returned to the previous version 

### ISSUE THREAD

**Issue by nnow991** [jaku/SnapCameraPreservation#15]
Hello, today modified version of the 1.21.0 version of Snap Chat suddenly stopped working for me and returned to the previous version of 1.21.0 - without lenses. 
To fix it i had to uninstall snap camera, reinstall it and go through Snap Camera Patcher again - I'm afraid it might happen again in the future. Any ideas what could have happened and how to prevent it?

**Comment by inMelodyy** [comment]
Happening for me aswell

**Comment by jaku** [comment]
It was a small hiccup while I was working on resolving issues for users outside of North/South America.

The app didn't revert it just couldn't communicate with my server. This has since been resolved. You will need to just kill it in task manager and reopen it.
