### ISSUE TITLE
Filters not working in Mac M1

### ISSUE THREAD

**Issue by naiadelali** [jaku/SnapCameraPreservation#18]
I am having issues with activating filters in Snap Cam version 1.21 on my M1 Mac. I would like to request assistance in identifying why the filters (lenses) are not working.

Thank you in advance for your help.

Sincerely, 

Lalli

![image](https://user-images.githubusercontent.com/7058175/216409444-6b754d53-1c6e-4a72-9654-9c7e5ef440c9.png)

**Comment by jaku** [comment]
Make sure the certificate file is installed and trusted. This appears to be the main issue MacOS users have.

**Comment by jaku** [comment]
This issue will be closed in a day if we do not hear back. Thanks.
