### ISSUE TITLE
This is going to fix snapcamera on pc forever?

### ISSUE THREAD

**Issue by Kellyjessy** [jaku/SnapCameraPreservation#19]
Hi Jaku, thanks for your help.  Damn I couldn't make a living otherwise.  So I must use SNAP camera and I m worried if after we patched the program this meant (post firewall block also) we can use it forever? I m not in coding lol, I paid a company to install it.  So what you think? I must think other way or I can relax that after your suggestions I got SNAP for years? Thankssssss

**Comment by jaku** [comment]
It will last for as long as I can handle the server costs. Currently I've paid close to around $80 for the hosting of the lenses in multiple regions on Amazon. The patch is getting more popular which depending on how much more popular the traffic costs could increase. However I am working on a solution that will make it easy for users to "self host" the files needed so it won't require my services. I'm on vacation for a week and will try to finish it after I get back. But this should help others like yourself feel safer in the software lasting for as long as possible.

**Comment by Kellyjessy** [comment]
Ok Matt! Thanks! :) honestly I don't have a clue about programming unfortunately lol. So someone does the fix for me. Omg you save my life and I m so grateful ❤️❤️❤️

**Comment by nnow991** [comment]
> It will last for as long as I can handle the server costs. Currently I've paid close to around $80 for the hosting of the lenses in multiple regions on Amazon. The patch is getting more popular which depending on how much more popular the traffic costs could increase. However I am working on a solution that will make it easy for users to "self host" the files needed so it won't require my services. I'm on vacation for a week and will try to finish it after I get back. But this should help others like yourself feel safer in the software lasting for as long as possible.

If you need any support with server costs, just let us know. A lot of people need this app and Im sure they are willing to help with the cost of maintaining it

**Comment by jaku** [comment]
Thanks @nnow991, I've had a donate button on my Twitch page for a while twitch.tv/jaku but recently setup a ko-fi account as well. https://ko-fi.com/jaku

I should be able to make a sponsor link on the repo but it's currently a little past 1am where I'm at and I'm gonna sleep for now.
