### ISSUE TITLE
Is this ever going to fix the big problem with snapcamera on amd that is the red box

### ISSUE THREAD

**Issue by Pickymarker** [jaku/SnapCameraPreservation#2]
Is this ever going to fix the big problem with snapcamera on amd gpus that is the red box https://imgur.com/a/70t7m7x or is this only ever going to be a way to use the filters still and not a way to fix the amd red box problem which i know other people with amd gpus have which makes snapcamera really a Nvidia thing only for most of the filters that are good like bald filter,child filter,etc.

**Comment by jaku** [comment]
That would go beyond the scope of this project. This is just for preservation, anything further requires a lot more work and time to reverse engineer. 

I have an AMD system and haven't noticed any issues but will try a few of the filters you mentioned.

**Comment by Pickymarker** [comment]
did you try out the filters to see the problem

**Comment by Pickymarker** [comment]
5700xt

**Comment by jaku** [comment]
I'm on the 6700 series so not really sure. But sadly it won't be something this project can resolve. It's just about the backing up of the lenses, if someone else figures out a fix it should work with all the lenses we have backed up.

**Comment by jaku** [comment]
Was actually able to reproduce this earlier now, but still not something I can resolve with this project.
