### ISSUE TITLE
"Jaku Snap Backup" Category Not Appearing

### ISSUE THREAD

**Issue by YourDLCMaster** [jaku/SnapCameraPreservation#20]
I installed Snap Camera version 1.21 from UptoDown (not the best idea, but the provided MD5s matched so it's fine), patched the executable in Program Files via the website and then swapped out the executable for the patched one (impersonating the filename, too). For some reason though, the alleged "Jaku Snap Backup" lens category is not showing up, just the filler lens slots, loading symbol at the bottom and no more shutdown notice.

Is there a step I missed or server I should add somewhere?

**Comment by jaku** [comment]
Sounds like something was missed.  Make sure the app was killed in task manager when you go to replace it.

**Comment by YourDLCMaster** [comment]
Yes, sorry! I forgot to quit it from the system tray, even before replacing the executable. This happens every time I ask for help lol, sorry again!
