### ISSUE TITLE
"My New Twin" Lens Not Found, Even After Pasting Link

### ISSUE THREAD

**Issue by ThePeeps191** [jaku/SnapCameraPreservation#21]
I tried to find My New Twin (which is a bit different from My Twin) by searching it and pasting https://lens.snapchat.com/20e98eba60bd4718924a1823c29ced90, however I could not find it.

Thanks for helping!

**Comment by jaku** [comment]
As mentioned in the unlocking lens area this no longer works after their shutdown of the app.
