### ISSUE TITLE
Needing a filter

### ISSUE THREAD

**Issue by vashdaman601** [jaku/SnapCameraPreservation#24]
I'll make this short and sweet. I'm looking for a filter and I have the link for the user who made them. Can they be added for use or is that 
 the end of it? https://www.snapchat.com/add/ky.haa

I'm trying to just get the anime face.

**Comment by jaku** [comment]
The first block of text on this project has the following about missing lenses. 

As of January 26th, 2023 the domain Snap Camera normally uses is now offline. We will not be able to recovery any lenses that are missing, please do not create issues looking for lenses or messaging me about it. If I find a way to bring missing lenses I will make an update but as of now, we do not have the ability to do this.

As mentioned if this changes I will update this page but there is nothing I can do to get missing lenses at this time.
