### ISSUE TITLE
Mac issue

### ISSUE THREAD

**Issue by a-m1234** [jaku/SnapCameraPreservation#25]
I am trying to access snapcamera but i cannot. I had it downloaded previously followed the proceduce but it keeps saying application not responding. so i uninstalled snapcamera and retried it and still it isnt working and says Application not responding. Is there something I can instead?

**Comment by jaku** [comment]
I can't really help with that issue. Sounds like something is wrong on the application and your computer itself that is causing that error. 

You might want to try and find either a different installer or try a slightly older version like 1.20. Mac users versions of the app don't matter like the PC version.

**Comment by CybaGirl** [comment]
> I am trying to access snapcamera but i cannot. I had it downloaded previously followed the proceduce but it keeps saying application not responding. so i uninstalled snapcamera and retried it and still it isnt working and says Application not responding. Is there something I can instead?

You could try a program called WhoCrashed and it will give you an idea on why it creashed. Or you can look in your event 
 manger to see what it says there.
 
 https://www.resplendence.com/whocrashed
 
 Once you know the error and you have an error number you can use a program called Error Lookup.
 
 https://www.henrypp.org/product/errorlookup
 
 These programs are free so no need for any payment.
