### ISSUE TITLE
New Lens

### ISSUE THREAD

**Issue by LuisAfonsoAlves** [jaku/SnapCameraPreservation#26]
Hi,
- is it possible to get some lens that were stored on a computer cache (but that were not backuped) to the new (backup) server?
- is there any way to still create new lens and somehow put them on the new (backup) server for us to use? 
Regards

**Comment by jaku** [comment]
Per the first paragraph of this repos readme. 

`As of January 26th, 2023, the domain Snap Camera normally uses is now offline. We will not be able to recover any lenses that are missing, please do not create issues looking for lenses or messaging me about it. If I find a way to bring the missing lenses I will make an update, but as of now, we do not have the ability to do this.`
