### ISSUE TITLE
Nikon Webcam Utility

### ISSUE THREAD

**Issue by BotAndis** [jaku/SnapCameraPreservation#27]
Is there a way to us my Nikon camera via the Nikon Webcam utility?
Because my camera (Webcam Utility) is not showing up, and I saw online that many had similar problems with their Cannon Utilities...
The only Option I found was to use third party apps which take the output from the camera and forward it to Snap Camera (but with a Watermark)

Preferably, I would use NVIDIA Broadcast, but that's also not showing up as an input option.

**Comment by jaku** [comment]
If the application didn't support it before this, I wouldn't be able to support it. You can use OBS to create a virtual camera that could be imported without a watermark. But presumably, you might be using OBS, so you'd need to run two instances of it.
