### ISSUE TITLE
Mac what am I doing wrong?

### ISSUE THREAD

**Issue by CalebWalz411** [jaku/SnapCameraPreservation#28]
Sorry to bother you Jaku but maybe you can help me figure out what i'm doing wrong. I downloaded the cert file then changed it to always trust and finally I copy pasted the code into my terminal. When i open the app everything is still blank but oddly enough i can access some of my filters that i saved in favorites although i have to randomly guess which ones they are because they all look like blanks. 

Thanks for your time and concern Jaku 
sincerely, a computer noob :( 

<img width="569" alt="Screenshot 2023-02-16 at 11 30 40 PM" src="https://user-images.githubusercontent.com/125627497/219542822-4f583f0a-9f64-4a53-bfb8-59dd706ac573.png">
<img width="535" alt="Screenshot 2023-02-16 at 11 31 13 PM" src="https://user-images.githubusercontent.com/125627497/219542825-b008d12a-e0f2-4f4c-a273-4d42808dd2d5.png">
<img width="952" alt="Screenshot 2023-02-16 at 11 32 28 PM" src="https://user-images.githubusercontent.com/125627497/219542828-cc04f4bd-19e1-496d-a63a-262f291ea7f7.png">

**Comment by jaku** [comment]
Did you completely close Snap Camera and reopen it? A reboot to be sure.

When you first close the app, it still hangs around in the Menu Bar at the top of the screen near the clock.

**Comment by CalebWalz411** [comment]
i copy pasted it into the terminal and it did not show me the IP nor the studio-app.snapchat.com entry

<img width="566" alt="Screenshot 2023-02-18 at 7 07 57 AM" src="https://user-images.githubusercontent.com/125627497/219857082-dcf87e06-676e-49ce-b450-e5787c882f8a.png">

**Comment by jaku** [comment]
I put the command in quotes. Please try again without the quotes.

**Comment by CalebWalz411** [comment]
here is the result of taking the quotes out 

<img width="562" alt="Screenshot 2023-02-18 at 1 07 02 PM" src="https://user-images.githubusercontent.com/125627497/219878741-06156bf8-df96-445b-8dab-7e773375dea8.png">

**Comment by luizpdlh** [comment]
@CalebWalz411 looks like your `/etc/hosts` file is not properly pointing to the right location.

On your first screenshot, after you pasted the command on Terminal and hit enter, you need to type your local password and hit enter so that the file gets properly edited.

**Comment by luizpdlh** [comment]
And I'm facing a similar issue even though I have the certificate applied and the ` /etc/hosts ` file edited:

![image](https://user-images.githubusercontent.com/74303248/219882510-8c69a214-1a72-4355-bab7-46e7c796f1cb.png)
![image](https://user-images.githubusercontent.com/74303248/219882526-34dd7725-7fb3-4219-a503-02fd5b72be05.png)
(It's in Portuguese, but it does say "Always Trust" lol.
![image](https://user-images.githubusercontent.com/74303248/219882548-d6b51d02-aa2f-4ea3-8884-f6ef93af8271.png)

**Comment by CalebWalz411** [comment]
Hello Luizpdlh thanks for your advice I tried to re-enter the command then put my local password and push enter and this was the result 

<img width="567" alt="Screenshot 2023-02-18 at 9 16 01 PM" src="https://user-images.githubusercontent.com/125627497/219906837-1ff6c7bf-dcd5-43c8-8408-938d3bb08795.png">

**Comment by jaku** [comment]
You're mistaking what they asked. 

Go back to the guide and run that command like before. In the first screenshot you sent you will see it asked for your password. When you type it it won't show. 

So go back and run the command, when it prompts type your password and press enter. It should then make the entry in your hosts file.

**Comment by CalebWalz411** [comment]
woohoo success :) thanks for you patience Jaku and help and thank you @luizpdlh for your help. 


<img width="564" alt="Screenshot 2023-02-19 at 10 07 54 AM" src="https://user-images.githubusercontent.com/125627497/219953439-41fa1923-558e-490a-be5f-fd1eca37d840.png">
<img width="600" alt="Screenshot 2023-02-19 at 10 08 08 AM" src="https://user-images.githubusercontent.com/125627497/219953443-e9c34193-6681-48a1-a55c-59f328d0bab8.png">
