### ISSUE TITLE
hello Jaku. help me for lens 

### ISSUE THREAD

**Issue by sonyawisp** [jaku/SnapCameraPreservation#31]
I'm a streamer. for two years I have been using the old version 1.18 with the mask "Airy Lens
by Nick Jackson". Please help me. How can I find it if it is not in two versions, and 21 by the way does not work in my country at all, I use 19 now. is it possible to create a patch for older versions, for example 18? or add my mask?
https://lens.snapchat.com/820b608931c54de39f47c22df4a94fb1?sender_web_id=c07fc59d-45b3-4b42-8d1d-8e303ca85645&device_type=desktop&is_copy_url=true

**Comment by jaku** [comment]
The lenses you can find in 1.19 will be the same lenses that are available for 1.18. All of these lenses we have were lenses used by users using my patch in January before the shutdown. This was the only way to really get them backed up. If your lenses was not used using my patch before then, it's not possible to use after the shutdown at this time.

There is a notice at the top of this repo that explains I am trying to find a way to get other lenses, but it is not quite yet possible.
