### ISSUE TITLE
Lenses doesnt work properly

### ISSUE THREAD

**Issue by Defowow** [jaku/SnapCameraPreservation#33]
Hi.

I'm getting some issues, and right after 5 uninstall / install, i would like some help.

Instead of all filters, i got a red rectangle on my face.. And i dont see how to solve this issue..

Do you got any advices ?

Thanks a lot...

**Comment by jaku** [comment]
This is an issue with AMD graphics cards, and is not something caused by my patching and was native to the original application. It's not something I can help resolve, unfortunately.
