### ISSUE TITLE
[IDEA] - Portable version if possible

### ISSUE THREAD

**Issue by littlemissybird** [jaku/SnapCameraPreservation#35]
Would it be possible to package as a portable version? This would be quite helpful for users without administrative rights to install.

**Comment by CybaGirl** [comment]
I can do this. But not right now as I am in the middle of doing a few things and wouldn’t be able to get to until the end of next week at the earliest.

**Comment by jaku** [comment]
It's not possible without administrator rights. The application creates an additional camera on the PC so that it can be used with other applications like Zoom. Without administrative access you'd only be able to view lenses in the application and not as a webcam.
