### ISSUE TITLE
Snap camera now works independently on my Mac, but not with online meeting tools such as MS Teams, Google Meet, etc. What can I do to fix it?

### ISSUE THREAD

**Issue by shawnhsu0910** [jaku/SnapCameraPreservation#38]
Hello! Using your instructions, I was able to make the snap camera work on a Mac. 
But, I wonder if it can't now work as a virtual camera in Microsoft Teams or Google Meets? I can no longer select the snap camera as a virtual camera when selecting the source of the cameras through those online meeting tools.

**Comment by jaku** [comment]
Reinstall the application, and it should re-prompt you for permissions. You don't need to follow any of the other mac instructions after reinstalling.

**Comment by nizaad** [comment]
Hi, I am having the same issue with my Mac. Can you please clarify your response? Do I reinstall SnapCamera? Thank you

**Comment by jaku** [comment]
Yes. Reinstalling the Snap Camera application from the installer will then ask for permissions that are needed to make that functionality work on the next time you open it.

**Comment by nizaad** [comment]
It doesn't, but thank you for your time.

**Comment by shawnhsu0910** [comment]
Yeah, me too. That doesn't work! I am still unable to find the option through the online meeting apps after reinstalling the Snap Camera app.
