### ISSUE TITLE
1.20.0

### ISSUE THREAD

**Issue by lordziggi** [jaku/SnapCameraPreservation#39]
can i use this version?

**Comment by jaku** [comment]
No, 1.21.0 and 1.19.0 are the 2 supported versions at the moment. Users that are on 1.21.0 reported issues with lenses not working for them, and the next version that worked for them was 1.19.0, so I don't see much reason to support 1.20.0 as it didn't solve the issues that 1.19.0 did.

**Comment by lordziggi** [comment]
Ok that's still good news I think. Is it possible to save the lenses I have still? I have most of the ones I want so if I'm better off not messing with if for a few extra lenses.

**Comment by jaku** [comment]
There are guides on backing up cached lenses but I don't have those instructions.
