### ISSUE TITLE
On the Mac how to run Snap Camera once file is patched

### ISSUE THREAD

**Issue by chazzzzy** [jaku/SnapCameraPreservation#4]
On the latest operating system of MacOS, you cannot run Snap Camera once you patch the Snap Camera executable file as the patched file is not executable.

Here is how you make the file executable once it's patched and copied into the MacOS folder (overwriting the old version)

Run Terminal and type the following:

`chmod 755 /Applications/Snap\ Camera.app/Contents/MacOS/Snap\ Camera`

It may tell you in a popup that Terminal is not allowed to alter the file, make sure you select Allow.

If you miss the popup or it doesn't happen and you still get the warning.. go to settings/privacy & security/ scroll down to where it tells you that you cannot run Snap Camera.. Authorize it... 

I then rebooted my computer and ran the chmod command again and it allowed me to run this time and then the app runs.

There may be an easier way to authorize Terminal to change the file into an executable, but I missed the popup message and couldn't get it back, so I did it in a roundabout way, but it works perfectly with the patched file now.

**Comment by jaku** [comment]
When you did this, did you get the correct categories showing that it's been patched? Every attempt I've had prevents the application from running because it's been modified against it's original code signature.

![image](https://user-images.githubusercontent.com/102187/213039420-41a9ee96-0744-4ca8-93df-2016277f4803.png)

This is what it should look like if it is in fact working, it's very possible this will work on some OS X versions and not others, so that might help.

**Comment by chazzzzy** [comment]
Yes.. this is what I am getting in the below image, categories showing:

Again.. I definitely had to change that patched file to make it executable and I ended up authorizing the app to run in the privacy settings as it said it was blocking the app.

I am running MacOS Ventura 13.1 on an Apple Mini M1

<img width="945" alt="Screenshot 2023-01-17 at 4 12 51 PM" src="https://user-images.githubusercontent.com/6125538/213041326-2a2fc6a0-787a-429c-b61b-0dd126f975da.png">

**Comment by jaku** [comment]
Right, but it's not actually connecting with my server since there isn't the added category I made. The new MacOS solution is fairly simple for users and doesn't require any patching. Give that a try though and you should see the correct category.

**Comment by chazzzzy** [comment]
Ah.. got it. I did your new instructions and it works perfectly now! 

Quick question. When you click the .crt file, it immediately asks you to add it to your keychain with iCloud clicked by default on the left. I selected in the pull-down login area instead. Can it be added to iCloud as well, or perhaps that is not a good idea as it could confuse other computers I have attached to my iCloud account?

Also, is there anything we should be doing on our end to add lenses to your repository? I have 3 lenses favorited currently.

<img width="1147" alt="Screenshot 2023-01-18 at 11 27 48 AM" src="https://user-images.githubusercontent.com/6125538/213276199-0b66d597-c176-47ce-a743-b25c33b376e5.png">

**Comment by jaku** [comment]
Honestly, not quite sure about that question. I would recommend against it if that is an option, installing it per-system is better.

So anything with a * in front means I've backed it up, but it doesn't hurt to just activate each lens you want to save to be sure.
