### ISSUE TITLE
patched version can't access the internet - Windows/1.21.0

### ISSUE THREAD

**Issue by yolotato** [jaku/SnapCameraPreservation#40]
hello! I was able to download and run the patched version but couldn't see the "Jaku Snap Backup" category or any of the filters. Tried uninstalling and repatching a few times, but kept getting the same issue "you have no internet connection" message where the filters usually are~ just wondering if it might be because I'm in Australia? Thanks!!

**Comment by jaku** [comment]
We have around 500,000 users in over 140 countries using this, so being in Australia shouldn't be an issue.

The domain may be blocked on your side for some reason, but even that seems odd. So it sounds like maybe it's not patching correctly. Try to disable ad-block on the patching site, if the patching doesn't run correctly, it will just give back the original file.

**Comment by yolotato** [comment]
disabling the ad blocker on chrome didn't work, so I opened the patching site on edge instead and that worked! thanks Jaku ^^
