### ISSUE TITLE
[Possible Source Code For Snap Camera]

### ISSUE THREAD

**Issue by Sans003** [jaku/SnapCameraPreservation#41]
I may have found a possible leaked source code of snap camera:
[Snap Camera Leak](https://github.com/jyx3/SnapChat-CameraSource)

**Comment by GForceWeb** [comment]
That's a 5 year old repo with a zip file with no further information from a user with no other credible repositories. 

At best, it's very old source code, at worst it's malware. I won't be unzipping that

**Comment by jaku** [comment]
Using any source code from Snap Camera would invalidate this project and cause more issues.
