### ISSUE TITLE
i have some wierd box around my face when i am using my graphic card

### ISSUE THREAD

**Issue by lumos675** [jaku/SnapCameraPreservation#43]
as you can see there is some box around my face when i am using simple retouch.whenever i disable my AMD radeon RX 6600 xt driver and use cpu's gpu i have no problem.but i can't keep disconnecting and connecting this cable every time i want to use this app do you have any idea how to fix this?
if i use a filter there is no issue but i love the simple retouch which the app offers the most

**Comment by lumos675** [comment]
here is the photo forgot to post it ... https://parsi.tube/up/uploads/1.jpg

**Comment by jaku** [comment]
https://github.com/jaku/SnapCameraPreservation/issues/33
https://github.com/jaku/SnapCameraPreservation/issues/2

duplicate ticket and something I am unable to fix
