### ISSUE TITLE
Problems with mac

### ISSUE THREAD

**Issue by Hansleonel** [jaku/SnapCameraPreservation#44]
since yesterday it does not work for mac, I have installed the certificate for 2 months and it worked fine but since today it is failing

**Comment by jaku** [comment]
Users reported it not working, but it is working now. Could have been an ISP thing or something with the host for a little bit. I'll investigate but, close the app completely and reopen it and it will work again.

**Comment by Hansleonel** [comment]
yeah, it's right, thanks for your awesome collaboration @jaku
