### ISSUE TITLE
overwriting settings.json 

### ISSUE THREAD

**Issue by REALtony4twenty** [jaku/SnapCameraPreservation#45]
https://www.youtube.com/watch?v=eEMWwZRVF-I - in this video I show using ptrumpis's version along-side yours

It allowed people to only run docker when downloading new lenses. So users could save on pc performance especially streamers. 
Today opening the Jaku patched version overwrites the settings.json with on that has no favorites or hotkeys etc.. where as before it would just launch and use what was already in the local folder. 

is their anyway to prevent this or maybe a patch to ptrumpis version that could allow it to run similarly?

**Comment by jaku** [comment]
Hmm, I haven't seen this other software before. I see it's actually pulling from my server too, which while overall fine, it would have been nice to get a heads up from the creator they were doing so. 

`So users could save on pc performance especially streamers.`

Running docker wouldn't save on PC performance, this would do the opposite. With my patch, it's a network request, when you get a new lens, it is then cached. So there are no additional requests/resources being used. But with a docker instance that would always be running and while most likely idle, that still takes up more resources of the CPU and RAM.

Docker seems like the wrong approach to this completely, I started another project that would allow for similar functionality that was a single install but I have not had the time to complete it. So while I understand a need for this, this seems to be an over-engineered solution.

As far as working to make this solution work with my patch, it would have to be done on their side. So I'd suggest making an issue on their GitHub.

**Comment by REALtony4twenty** [comment]
well hopefully this can lead to a collaboration, I would like to see it all boil down to a single install for the future and cover it in a video so users can get their snap cap back and access to new ones without be afraid of the currently available solutions and what it takes to get them working.
