### ISSUE TITLE
[enhancement] fix issue preventing use with EOS webcam utility/obs virtualcam

### ISSUE THREAD

**Issue by Fireeyeeian** [jaku/SnapCameraPreservation#46]
Snap camera doesn't seem to work directly with EOS webcam utility.
 Eos is an option in the dropdown for selecting a camera but it just gives the ol' "No available camera input". as for obs virtual camera that straight up doesn't show up. 

The issue is that in order to use a dslr or at least cannons you have to run your camera  through different apps to get it into snap and then to discord  adding significant delay to the final output. 
Either eos>obs>splitcam>snap>discord or eos>manycam>snap>discord

**Comment by jaku** [comment]
Out side of the scope of this project. Good luck with what you're trying to do.
