### ISSUE TITLE
Changing the Camera Name "Snap Camera"

### ISSUE THREAD

**Issue by ZuherLaith** [jaku/SnapCameraPreservation#47]
Hi,

I'm looking into changing the driver name of snap camera to another name
it seems to be working changing in **registry editor**, but the application does not export video correctly,
also when I changed the camera name, in device manager > cameras, "Snap Camera" kept its name without changing

what am I missing?
any information would be helpful, I really need to change its name since its flagged as "virtual camera" in many websites and can only be used using OBS.

**Comment by jaku** [comment]
Out of scope for this project.
