### ISSUE TITLE
Question about SnapCam Preservation

### ISSUE THREAD

**Issue by gitihobo** [jaku/SnapCameraPreservation#50]
I'm doing to snap-camera.en.uptodown.com/windows download process combined with Jaku's patch. I am wondering if this is making it so the install is completely local or is someone running a server to keep it alive. Regardless, can we implement it completely locally somehow? Also, is the exe from the uptodown website safe? I don't want to get pwned lol

**Comment by jaku** [comment]
Someone can take this repo to make their own instance. The server isn't going anywhere, I've run projects for 10+ years without outside support so I don't have any plans to let that happen to this one and if it does I'll make sure people know ahead of time and get steps on how to do it.

This repo shows how you can verify the files before installing them.

**Comment by gitihobo** [comment]
Thanks Jaku, I mainly want it to be local because if god forbid something happens to you, we lose this project at the same time. I figured out how to verify the exe but is it hard to make my own local server for free so I can be responsible of my copy of this github?
