### ISSUE TITLE
Snap camera doesn't work on Mac M1

### ISSUE THREAD

**Issue by XinyeYang** [jaku/SnapCameraPreservation#53]
![](https://github.com/jaku/SnapCameraPreservation/assets/61686580/72352b83-1e7e-407c-9fe4-498e68b84dbb)

**Comment by jaku** [comment]
It works on M1 cause that is what I use. 

Everything looks correct from what you are sharing, but it's possible a proxy setting is overwriting the /etc/hosts file value.

Is this a work machine, and do you have any proxy settings under the networking?

**Comment by XinyeYang** [comment]
This is my own personal computer and I have exited all proxy.

It's weird that when I open "Run Snap Camera on system startup", it works correctly when I restart my Mac.

Once I close Snap Camera completely and then reopen it, it doesn't work.

**Comment by sdyura** [comment]
i just tried to install this and it is also not working on my M1 mac

**Comment by soonkyugongju** [comment]
I've installed using the instructions but I'm still getting no access to the lenses. One of my backup lens also disappeared
<img width="943" alt="Screenshot 2023-07-12 at 11 23 16 AM" src="https://github.com/jaku/SnapCameraPreservation/assets/139306662/56ff8c0b-3dd7-442a-bb80-d45af8669719">

**Comment by jpgninja** [comment]
Is it possible @XinyeYang had a bad version of snap cam, meaning either not `1.21` or an altered `1.21` ?

@jaku since you use it, are you able to post the `checksum` of the **Mac 1.21 pkg**? it's available for download but the checksums are all over the place and only the windows version appears in the repo instructions.

**Comment by XinyeYang** [comment]
I have checked the version, it's 1.21.

I encountered a problem before, which may have been due to network issues. Without using VPN (or Clash VPN App), it wouldn't work, but I replaced it with a paid VPN app and everything was fine.
