### ISSUE TITLE
Some filters are unavailable

### ISSUE THREAD

**Issue by soonkyugongju** [jaku/SnapCameraPreservation#62]
They cannot be searched on snap camera but are in Lens Studio. Some of this creators lenses are available, but some are not.
Example: https://lens.snapchat.com/ca5a59189c974aaf9cd3a5c7a3254ee9

**Comment by ewwink** [comment]
it use static data that can be found on https://github.com/jaku/SnapCameraPreservation/tree/main/server/src/json
we need to setup private server then update these files, for search function we need scraper.
