### ISSUE TITLE
Accidental Favorite Deleted

### ISSUE THREAD

**Issue by EnderGirl1500** [jaku/SnapCameraPreservation#63]
I accidentally clicked the star on one of my favorited filters. The thing is that this specific filter was one of the imported ones from the original Snap Camera and is no longer available in the patch. It's the only one I use and I really need to know if it could've gone to another folder in my computer so I can recover it

**Comment by CybaGirl** [comment]
What was the filter called?

You could try recovery software like R-Studio.

**Comment by EnderGirl1500** [comment]
it was called "Hot pink" I think, none of the ones that appear to me is the one I want
