### ISSUE TITLE
No longer working with macOS Sonoma

### ISSUE THREAD

**Issue by sewqawsdewq332** [jaku/SnapCameraPreservation#66]
I just updated to Sonoma 14.1 and now Snap doesn't show up as a camera device in any browser or app. 

Cleared cache, reset permissions, and re-downloaded but nothing fixes it.

**Comment by CalebWalz411** [comment]
Im having the exact same issue

**Comment by jaku** [comment]
https://support.apple.com/en-us/HT213969

**Comment by a-m1234** [comment]
Does this mean we cannot use it?

**Comment by a-m1234** [comment]
if i follow the "Restore legacy video device support" on the link provided will that fix the issue?

**Comment by jaku** [comment]
Yes, that will fix it.

**Comment by sewqawsdewq332** [comment]
I followed

> https://support.apple.com/en-us/HT213969

Thanks - I followed these instructions but got the below error:


> -bash-3.2# system-override legacy-camera-plugins-without-sw-camera-indication=on

> Volume on disk32 failed to mount 

> This is an encrypted and locked APFS volume; use “diskutil apfs unlockVolume”

**Comment by sewqawsdewq332** [comment]
> if i follow the "Restore legacy video device support" on the link provided will that fix the issue?

Did this work for you?

**Comment by sewqawsdewq332** [comment]
Solved - had to run `diskutil apfs list` and then find the disk3s2 Volume Identifier, then run `diskutil apfs unlockVolume <VolumeIdentifier>` and finally run `system-override legacy-camera-plugins-without-sw-camera-indication=on`.

Thanks @jaku!

**Comment by Pato2222** [comment]
It doesn’t work anymore, it doesn’t mount to disk3s2 it tries mounting to disk3s5, which makes everything not work 

-bash-3.2# system-override legacy-camera-plugins-without-sw-camera-indication=on
Volume on disks failed to mount
This is an encrypted and locked APFS Volume; use "diskutil apfs unlockVolume" system-override: failed to mount volume (disk3s5)
