### ISSUE TITLE
Renovate macos certificate

### ISSUE THREAD

**Issue by VinyLimaZ** [jaku/SnapCameraPreservation#68]
The macos certificate of the snap-camera will due on 2024/01, does it need to be renovated? Or could we add again and the time is extended?

**Comment by jaku** [comment]
Pushed an update today to this repo that will no longer require the certificate or modifying the hosts file.

**Comment by Martsnapcam** [comment]
Many thanks for all your work. I lost snapcam as an available source when I updated Mac OS a month or two ago when I wanted to add a source to OBS. I've just performed the terminal fix and I still don't have snapcam as a source. Snapcam itself works fine but not available to use.
Many thanks Mart 16th Jan 11:20am
