### ISSUE TITLE
SnapCamera not showing as available camera in Zoom?

### ISSUE THREAD

**Issue by Ethyyy54** [jaku/SnapCameraPreservation#69]
Snap Camera app is working just fine, but I can't get it to show up as a camera option is Zoom or Discord. 

Can anyone share steps that will fix this?

**Comment by frankros91** [comment]
I'm experiencing this as well.  I tried to revoke camera permissions to zoom and re-install snapcam...but still nothing

**Comment by ccarmel** [comment]
same here. instalation on mac went smooth.
filters are loaded fine, but snap camera is not sowing as video input in zoom nor facetime.
any idea how to fix this?

**Comment by ccxxv** [comment]
I'm having the same issue with OBS not showing Snapcam as an available video source, as OBS was installed first. I tried revoking access and reallowing but this did not work, and unfortunately OBS does not appear in that list. Do you have any other recommendations?

**Comment by jaku** [comment]
https://support.apple.com/en-us/108387

Have you followed the instructions on the apple page above? It sounds like you're having those issues rather than the other similar issues.

**Comment by ccxxv** [comment]
> https://support.apple.com/en-us/108387
> 
> Have you followed the instructions on the apple page above? It sounds like you're having those issues rather than the other similar issues.

Thank you! This solved my problem! 
You're the boss !

**Comment by kineticscreen** [comment]
> EDIT: .... The screen on OBS once the video input is added is just black as opposed to showing the video feed from Snap Cam 

Same issue here.

**Comment by jaku** [comment]
I updated the mac install to try and resolve these issues, if you are currently patched or not, you can run it and let me know if it resolves the issue for you or not.
