### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by gooselass** [jaku/SnapCameraPreservation#7]
Snap Camera lenses have helped me spend time with friends during COVID using my webcam despite having very, *very* bad body dysmorphia. I don't know if this is the most appropriate place to say it, but thank you so much for creating this tool. Its impact is felt.

Sorry for creating an "issue"; please consider it solved.

**Comment by jaku** [comment]
No worries about creating a issue for this. I'm glad I could help. Thank you for sharing.
