### ISSUE TITLE
An Issue with the desktop app

### ISSUE THREAD

**Issue by DJ-Rabbit** [jaku/SnapCameraPreservation#70]
Jaku everything works great except the fact that the hotkeys will NOT work with the program if it is minimized. It has to be maximized the same time as OBS and be on top of OBS for the hotkeys to work. Has anybody found a work around for this? Possibly docking it? I'm not sure, I ran out of ideas and this seems to be the only place people are talking about this program anymore.

**Comment by jaku** [comment]
I believe this has always functioned like this. Nothing I did to the application should/would have broken this.

Perhaps an application like auto-hot key can be used in addition to focus on the snap camera input for the hotkeys so it can be activated anywhere?

**Comment by DJ-Rabbit** [comment]
Yea I knew it had nothing to do with your work on the application, I just was not sure if this has been brought up or if you knew a simple fix. I'll check auto hotkey and hopefully someone reading this knoes of some ideas. Thanks again !!! Excited for the future of this project !!!

**Comment by jaku** [comment]
No worries, I honestly wasn't sure if it worked before or not, but suspected it didn't.

With AHK, I'm pretty sure the command you are looking for is ControlSend and it lets you set a window to send the keystroke to. Not the best solution but it should in theory work.

Additionally, I am looking to bring back some of the Twitch features they had in an older version, not sure how feasible it is yet, but some of the code is still there.
