### ISSUE TITLE
Mac patch issue 2024

### ISSUE THREAD

**Issue by visionary77** [jaku/SnapCameraPreservation#74]
Hello, 

I am having issues on mac since the old patch stopped working I have installed the new one but any browser I use is not seeing the snap camera input. I see all the filters in the app properly but it's just not porting thru to the browsers. I have tried installing an older version (1.9) as well as the latest (1.21). I have also checked the camera permissions but I can't seem to find where the problem is. 

Any idea how to fix it?

**Comment by KsiBart** [comment]
Restoring legacy video device support solves the issue.

https://support.apple.com/en-us/HT213969
