### ISSUE TITLE
Filter Snap Inc. Lenses

### ISSUE THREAD

**Issue by rods012** [jaku/SnapCameraPreservation#8]
If there is a way to filter the Snap Inc. Lenses so that they are all visible it would be amazing! Currently it is very hard to get most of them.

**Comment by jaku** [comment]
This is completed. You can use it by typing ``(by: Snap Inc.)`` in the search, or any other creator name.

![image](https://user-images.githubusercontent.com/102187/214910129-1faf8bab-9587-4c6c-8f56-dc9747e70534.png)
