### ISSUE TITLE
Streamyard / Sanoma 14.3.1

### ISSUE THREAD

**Issue by sabrinajinx** [jaku/SnapCameraPreservation#81]
I am still not able to get the app to work with streamyard. It allows me to select snap camera as a camera source but the preview is a yellow box.

I reinstalled the operating system on my computer to the current version Sonoma 14.3.1 (i'm not sure if there are directions for restoring the legacy video device support with this update. I used the directions for Sonoma 14.1 which may be the issue)
I restored legacy video device support (for Sonoma 14.1)
Then I deleted snap camera, reinstalled it, and patched the software
Restarted the computer
and checked the privacy settings on the camera 

Please let me know what your recommendations are for working around this. The toolbar at the top of my computer shows an indication that snap camera is running but when I click on the green box, it doesn't show me a preview with the filter, It just shows the default facetime camera. Thank you for your help!

<img width="264" alt="Screenshot 2024-02-10 at 2 05 22 PM" src="https://github.com/jaku/SnapCameraPreservation/assets/159662465/5d92e843-8067-47f3-8eaa-c44e9545e5ec">

<img width="489" alt="Screenshot 2024-02-10 at 2 05 44 PM" src="https://github.com/jaku/SnapCameraPreservation/assets/159662465/dad489c9-8f91-4a38-8858-25b117309338">

<img width="347" alt="Screenshot 2024-02-10 at 2 06 21 PM" src="https://github.com/jaku/SnapCameraPreservation/assets/159662465/eb7b2bbe-07ab-4a9e-8b3b-380e9e7176be">

**Comment by CannibalKush** [comment]
Can I ask what the Snap Camera app itself is showing during all this? Does it load the list of filters correctly, for example?

**Comment by sabrinajinx** [comment]
Yes it loads the filters with the patch script.
