### ISSUE TITLE
Working for Skype, but not web integrated

### ISSUE THREAD

**Issue by elliereaux** [jaku/SnapCameraPreservation#82]
So im an adult worker and use well some online platforms. Its finally working with skype and normally, but i cant get it to work online.

At this point i'm just trying to figure out how to work around the jaku version and just backup my existing lenses from my old laptop (which works fine) MAC. I've backed up cache, application support and for some reason my favorite lenses arent showing up....HELP!!! galileojinx@yahoo.com if you have a solution

**Comment by vmodha** [comment]
I had these problems too, fixed it by following this solution:
https://github.com/jaku/SnapCameraPreservation/issues/76#issuecomment-1941748619

Followed by reinstalling snap cam (without unintalling the previous one), and running all of the mac instruction from scratch (the terminal command). 

Now everything works
