### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by frankbasti** [jaku/SnapCameraPreservation#83]
I am trying to recompile for mac to use my own server as a reverse proxy.   

Im a little confused about needing to use a donain which is same length as yours / snap.  

snapchatreverse.jaku.tv

studio-app.snapchat.com

why does it need to be same length?
For example would lens.jaku.tv not work??

thanks

**Comment by jaku** [comment]
Changing the length by adding or removing bytes from the program will change offsets in other areas of the program. You don't need the same length domain, you could do a shorter one and then add additional pathing on the other side of the URL but I find matching the host length to be cleaner and easier.

**Comment by frankbasti** [comment]
Thank you for the clarification, and all your work!
