### ISSUE TITLE
When I using a Snap camera, the Mac gets very hot and the video slows down

### ISSUE THREAD

**Issue by Lanka19** [jaku/SnapCameraPreservation#84]
Hello Jaku! I want to express my gratitude for giving me the opportunity to use the Snap camera, it’s really cool, thank you.
But unfortunately I encountered 2 problems, maybe you can help, I would be happy.
I use a MacBookAir M1 16gb, when I turn on Snap Camera in OBS or Skype, my computer gets very hot, after a few minutes the picture starts to slow down and lag, without even starting the online broadcast. CPU Snap camera 150% , OBS 120% ..That is, I cannot fully use the program for streaming, since the picture freezes all the time. Can anything be done about this?
The second problem is when rebooting the MAC, my obs, skype and etc stop seeing Snap Camera, I have to reinstall it every time through the terminal. This problem happened on both Ventura and Sonoma.
Help me please

**Comment by jaku** [comment]
This is most likely gonna be an issue for M1/2/3 Mac's and the snap camera app was made for the Intel Macs and we won't be able to change that.
