### ISSUE TITLE
Error from Terminal

### ISSUE THREAD

**Issue by cathellis** [jaku/SnapCameraPreservation#85]
Hey Jaku, I am getting the following message in terminal.

Unable to complete the application move, check that Terminal has permission under App Management and try again.

Please can you advise what I need to do?

**Comment by cathellis** [comment]
This is the full message...

Please wait while we download Snap Camera
Waiting to make sure Snap Camera is installed
This part will take a while. Please be patient.
cp: /Applications/Snap Camera.app/Contents/MacOS/Snap Camera: Operation not permitted
Unable to complete the application move, check that Terminal has permission under App Management and try again.

**Comment by jaku** [comment]
The script should be opening a browser with instructions on what that is and how to configure it.
