### ISSUE TITLE
Snap Camera working in the snap app but not recognised as a source anywhere (MAC Sonoma 14.3.1 M3)

### ISSUE THREAD

**Issue by ngarpedio** [jaku/SnapCameraPreservation#94]
With Mac Sonoma 14.3.1 M3 Pro Chip I can sucessfully install the app from terminal, using admin priviledges.

Once I open the app it works flawless but every time I access the camera from a browser or zoom app, snap camera does appear as a video source.

**Comment by gernar** [comment]
I found a discussion here https://github.com/ptrumpis/snap-camera-server/discussions/76 but for me it not entirely worked. Snap camera appeared in devices but gives no image (black screen)

**Comment by gernar** [comment]
quick fix for OBS: select snap camera as application capture device. Then yellow screen is gone. Idk how it works but it works.

**Comment by ngarpedio** [comment]
@jaku saw its marked as solved, is this solved with the terminal command for mac? Have tested and still issue present

**Comment by jmarie062199** [comment]
how to appear snap camera in google chrome in mac? i cant see it on the selections of cameras
