### ISSUE TITLE
Unlock Lenses?

### ISSUE THREAD

**Issue by lowlune** [jaku/SnapCameraPreservation#97]
> @Unlock Lenses?
> The below will no longer work now that they shut down the servers.
> 
> Since starting this project, I learned that some lenses are not available in the search of Snap Camera and instead must be directly searched for by their URL in the search box. I'm happy to report that these also work on this project, and as an extra bonus I made it so that you can use links like https://lens.snapchat.com/81f476238cf84615ba349efe82b36c27 instead of the https://www.snapchat.com/unlock/?type=SNAPCODE&uuid=81f476238cf84615ba349efe82b36c27&metadata=01 style links.
> 
> The above will no longer work now that they shut down the servers

The lenses are still available in this format [https://www.snapchat.com/lens/a4a202445b994be4924b59064621d661?sender_web_id=b5976f4e-5f94-488c-b751-1278456f4cb4&device_type=desktop&is_copy_url=true](https://www.snapchat.com/lens/a4a202445b994be4924b59064621d661?sender_web_id=b5976f4e-5f94-488c-b751-1278456f4cb4&device_type=desktop&is_copy_url=true).

Is it not possible to mirror these lenses onto the new SnapCamera server?

**Comment by lowlune** [comment]
gigachad

**Comment by andres-vizcaino** [comment]
apparently, it is not possible
